# Generated by Django 4.2.4 on 2023-08-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_name', models.CharField(max_length=255, verbose_name='Название дисциплины')),
                ('tutor', models.CharField(max_length=255, verbose_name='ФИО преподавателя')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor', models.CharField(max_length=255, verbose_name='Аудитория')),
                ('korpus', models.CharField(max_length=255, verbose_name='Корпус')),
                ('time_note', models.TimeField(verbose_name='Время начала')),
                ('date_note', models.DateField(verbose_name='Дата')),
                ('places', models.IntegerField(verbose_name='Количество человек')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapis.disciplines', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Дисциплина (запись)',
                'verbose_name_plural': 'Дисциплины (записи)',
            },
        ),
    ]
