# Generated by Django 4.2.4 on 2023-08-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zapis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('particular', models.CharField(max_length=255, verbose_name='Отчество')),
                ('discipline_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapis.note', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Студент - запись',
                'verbose_name_plural': 'Студенты - записи',
            },
        ),
    ]
